// <auto-generated />
using Klika.ResourceApi.Database.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Klika.ResourceApi.Database.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20210629234127_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Klika.ResourceApi.Model.Entities.TemplateDbContext.TemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TemplateProperty1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TemplateProperty2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TemplateProperty3")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TemplateTable");
                });
#pragma warning restore 612, 618
        }
    }
}
